config/routes.rb
Cloud::Application.routes.draw do

 resources :resumes , :only => [:create, :destroy, :index, :new]
  root to: "resumes#index"
  devise_for :users
  get '/resumes/create' => 'resumes#create'
  post '/resumes/connect' => 'resumes#connect'
  get '/resumes/reg' =>  'resumes#reg'
  get '/resumes/show' =>  'resumes#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == :admin
      can :manage, :all
    elsif user.role == :user
      can :manage, [Resume]
    else
      can :read, [Resume]
    end
  end
end

app/models/inquiry.rb
class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :message, :nickname
  
  validates :name, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
  validates :message,
            :length => { :minimum => 10, :maximum => 1000 }
            
  validates :nickname, 
            :format => { :with => /^$/ }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => email,
      :subject => "Website inquiry",
      :body => message,
      :html_body => simple_format(message)
    })
  end
      
  def persisted?
    false
  end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :attachment, :name, :file_size
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  belongs_to :user
  validates_presence_of :attachment
  validates_uniqueness_of :name
  before_save :update_attachment_attributes
  private


  def update_attachment_attributes
    if attachment.present?
      self.file_size = attachment.file.size
    end
  end
  before_create do
    self.name = self.attachment.original_file
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password,:allocated_space, :password_confirmation, :remember_me, :space, :role
  # attr_accessible :title, :body
  has_many :resumes

  ROLES = %w[admin user author]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.deliver
      render :thank_you

    else
      render :new
    end
  end
end

app/controllers/managingusers_controller.rb
class ManagingusersController < ApplicationController
  before_filter :check_admin
  require 'sys/filesystem'

  def index
    @users =  User.all
    stat = Sys::Filesystem.stat('/')
    @mb_available = stat.block_size * stat.blocks_available / 1024 / 1024
    @mb_total = stat.block_size * stat.blocks/ 1024 / 1024
  end

  def new
  end

  def create
  end

  def update
    @user = User.find(params[:id])

  end

  def update_allocated_user_space
    @user = User.find(params[:ID])
    @user.update_attributes(space:params[:space])
    flash[:notice] = "Space allocated Successully"
  end

  def destroy
    @user = User.find(params[:id])
    if @user
      @user.destroy
      redirect_to managingusers_path
    end

  end

  def getspace
    stat = Sys::Filesystem.stat('/')
    @mb_available = stat.block_size * stat.blocks_available / 1024 / 1024
  end
end

app/controllers/resumes_controller.rb
require 'dropbox_sdk'
class ResumesController < ApplicationController
  before_filter   :authenticate_user!
  def index

        @user = current_user
        @resumes = @user.resumes.all

  end

  def connect


    session[:code] = params[:code].to_s
    session[:access_token], session[:user_id] = session[:flow].finish(session[:code])
    session[:client] = DropboxClient.new(session[:access_token])
    puts "linked account:", session[:client].account_info().inspect
  end

  def new
    @resume = Resume.new
  end

  def create

      @resume =Resume.new(params[:resume])


      #access_token = session[:access_token]


      @user = current_user
     @resume.user_id = @user.id
    if @resume.save!
      file = open("#{Rails.root}/public#{@resume.attachment_url}")
      response = session[:client].put_file("#{@resume.name}", file )
      puts "uploaded:", response.inspect
       @resume.destroy



     # contents, metadata = client.get_file_and_metadata("#{@resume.name}")
     # open("#{@resume.name}", 'w') {|f| f.puts contents }



    else
      render "new"
    end

end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  def reg

    session[:APP_KEY] = 'x48vnwl4fgnelmx'
    session[:APP_SECRET] = 's2ixzu5cfr6wydi'
    session[:flow] = DropboxOAuth2FlowNoRedirect.new(session[:APP_KEY], session[:APP_SECRET])
    @authorize_url = session[:flow].start()

  end

  def show
    @root_metadata = session[:client].metadata('/')

  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/managingusers_helper.rb
module ManagingusersHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/inquiries/_form.html.erb
        <div class="row">
          <div class="span2"></div>


            <div class="span8 well">

                                     <%= form_for @inquiry,:html => {class: '.form-inline'} do |f| %>
                                        <% if inquiry.errors.any? %>
                                        <ul>
                                          <% inquiry.errors.full_messages.each do |msg| %>
                                            <li><%= msg %></li>
                                          <% end %>
                                        </ul>
                                      <% end %>

                                      <div style="display: none;">
                                        <%= f.label :nickname %><br/>
                                        <%= f.text_field :nickname %>
                                      </div>


                                        <label>Name</label>
                                        <%= f.text_field :name, class:"span3" %>



                                        <label>Email</label>

                                        <%= f.text_field :email,class: "span3" %>




                                        <label>Message</label>
                                        <%= f.text_area :message,class:"input-xlarge span5", rows: "8" %>
                                        <br><br>

                                         <div>
                                        <%= f.submit "Send", class:"btn btn-primary  " %>
                                         </div>
                                    <% end %>
            </div>


      </div>

app/views/inquiries/new.html.erb
<%= render 'form', :inquiry => @inquiry %>

app/views/inquiries/thank_you.html.erb
<h1>Thank you!</h1>
<p>Your inquiry has been sent and we'll be in touch as soon as possible.</p>

app/views/layouts/_footer.html.erb
<br><br><br><br><br>
<div class="container marketing">
<div class="row">
<footer>
  <p class="pull-right">
    <a href="#">Back to top</a>
  </p>
  <p>
    © 2013 Company, Inc. ·
    <a href="#">Privacy</a>
    ·
    <a href="#">Terms</a>
  </p>
</footer>
</div>
</div>

app/views/layouts/_marketing.html.erb
<div class="container marketing">
  <div class="row">
    <div class="col-lg-4">
      <%=image_tag ("m1.png"),:class=>"img-circle" , :style => "height :150px; width :150px"%>
      <h2 >Heading</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p>
        <a class="btn btn-default" role="button" href="#">View details »</a>
      </p>
    </div>
    <div class="col-lg-4">
      <%=image_tag ("cloud.png"),:class=>"img-circle" , :style => "height :150px; width :150px"%>
      <h2>Remote Storage</h2>
      <p>You can upload any kind of files any time by using our awesome service.Our application uses the remote storage for the storage purposes.Frequent backups of the data make sure the integrity and availability. <p>
        <a class="btn btn-default" role="button" href="#">View details »</a>
      </p>
    </div>
    <div class="col-lg-4">
      <%=image_tag ("drop.jpeg"),:class=>"img-circle", :style => "height :150px; width :150px"%>
      <h2>Drop Box</h2>
      <p>The safety and the security of the data has the prime importance. We use the Drobox service to store the images.You can download or upload any kind of images. Your images will be available to you any time.</p>
      <p>
        <a class="btn btn-default" role="button" href="#">View details »</a>
      </p>
    </div>

  </div>
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">
        Security of cloud storage.
        <span class="text-muted">It'll blow your mind.</span>
      </h2>
      <p class="lead">When data is distributed it is stored at more locations increasing the risk of unauthorised physical access to the data. For example, in cloud based architecture, data is replicated and moved frequently so the risk of unauthorised data recovery increases dramatically. (e.g. disposal of old equipment, reuse of drives, reallocation of storage space) The manner that data is replicated depends on the service level a customer chooses and on the service provided. Different cloud vendors offer different service levels. Risk of unauthorized access to data can be mitigated through the use of encryption, which can be applied to data as part of the storage service or by on-premises equipment that encrypts data prior to uploading it to the cloud.</p>
    </div>
    <div class="col-md-5">
      <%=image_tag ("cloud2.jpg"), :style => "height :500px; width :500px"%>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-5">
      <%=image_tag ("11.jpg"), :style => "height :500px; width :500px"%>
    </div>
    <div class="col-md-7">
      <h2 class="featurette-heading">
        All about Dropbox.
        <span class="text-muted">See for yourself.</span>
      </h2>
      <p class="lead">Both the Dropbox server and desktop client software are primarily written in Python. The desktop client uses GUI toolkits such as wxWidgets and Cocoa. Other notable Python libraries include Twisted, ctypes, and pywin32. Dropbox ships and depends on the librsync binary-delta library (which is written in C)</p>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">
        And lastly,
        <span class="text-muted">Here we are</span>
      </h2>
      <p class="lead">The distinction between operating system and middleware functionality is, to some extent, arbitrary. While core kernel functionality can only be provided by the operating system itself, some functionality previously provided by separately sold middleware is now integrated in operating systems. A typical example is the TCP/IP stack for telecommunications, nowadays included in virtually every operating system.</p>
    </div>
    <div class="col-md-5">
      <%=image_tag ("it.jpg"), :style => "height :500px; width :500px"%>
    </div>
  </div>
  <hr class="featurette-divider">

</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>

          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in?  %>

                <li>
                  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
                </li>
                <li>
                  <%= link_to('Edit account', edit_user_registration_path) %>
                </li>


            <% else %>
                <li>
                  <%= link_to('Login', new_user_session_path)  %>
                </li>
                <li>
                  <%= link_to('Sign up', new_user_registration_path)  %>
                </li>
            <% end %>

          </ul>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_slider.html.erb
<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <%= image_tag ("z.jpg"), :style => "height :480px; width :1550px" %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag ("c.jpeg"), :style => "height :480px; width :1550px" %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag ("y.jpg"), :style => "height :480px; width :1550px" %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag ("a.jpeg"), :style => "height :480px; width :1550px" %>
      <div class="carousel-caption">
        <p>Caption text here</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
  <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloud</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<%= render 'layouts/slider' %>
<div class="container marketing">
  <div class="col-lg-11">
<%= yield %>
</div>
</div>
<%= render 'layouts/marketing' %>
<%= render 'layouts/footer' %>







</body>
</html>

app/views/managingusers/destroy.html.erb
<h1>Managingusers#destroy</h1>
<p>Find me in app/views/managingusers/destroy.html.erb</p>

app/views/managingusers/getspace.html.erb
hello world
<%= @mb_available %>

app/views/managingusers/index.html.erb
      <script type="text/javascript" src="https://www.google.com/jsapi"></script>
      <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
          google.setOnLoadCallback(drawChart);
          function drawChart() {
              var data = google.visualization.arrayToDataTable([
                  ['Language', 'Speakers (in millions)'],
                  ['Total',  <%= @mb_total %>],
                  ['used', <%= @mb_total %>-<%= @mb_available %>],

              ]);

              var options = {
                  legend: 'none',
                  pieSliceText: 'label',
                  pieStartAngle: 100

              };

              var chart = new google.visualization.PieChart(document.getElementById('piechart'));
              chart.draw(data, options);
          }
      </script>
      <div id="piechart" style="width: 400px; height: 300px; margin-left: 500px; margin-top: -70px"></div>

<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Email</th>
    <th>Last signed in </th>
    <th>Created </th>
    <th>Allocated Space </th>
    <th>Delete</th>
    <th>Update</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <% if user.email == 'admin@cloud.com' %>
            <%- else %>
        <td><%= user.email %></td>
            <td><%= distance_of_time_in_words(user.last_sign_in_at, Time.now) %> ago</td>
        <td><%= distance_of_time_in_words(user.created_at, Time.now) %> ago</td>
            <td><%= user.space %> Mb</td>
        <td><%= button_to "Delete",  managinguser_path(user), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{user.email}?" %></td>
        <td><%= button_to "Uppdate",  managinguser_path(user), method: :put, class: "btn btn-success" %></td></td>
      </tr>
        <% end %>
  <% end %>
  </tbody>
</table>

app/views/managingusers/new.html.erb
<h1>Managingusers#new</h1>
<p>Find me in app/views/managingusers/new.html.erb</p>

app/views/managingusers/update.html.erb
<h2>Update Users </h2>

<br>

<table class="table">
  <%= form_tag(:action => 'update_allocated_user_space', :method=>'post') do %>
     <tr>
       <td>

         <h4>ID &nbsp</h4>
       </td>
       <td>
         <%= text_field_tag "ID",@user.id,readonly:"true"%>
       </td>
       </tr>
      <tr>
       <td>
         <h4>Email &nbsp</h4>
       </td>
       <td>
         <%= text_field_tag "email",@user.email,readonly:"true"%>
       </td>
      </tr>
      <tr>
        <td>
          <h4>Space</h4>
        </td>
        <td>
          <%= text_field_tag "space",@user.space%>mb
        </td>
      </tr>
      <tr>
        <td>
          <h4>Role</h4>
        </td>
        <td>
          <%= text_field_tag "role",@user.role,readonly:"true"%>
        </td>
      </tr>
      <tr>
        <td>
        </td>
        <td>
          <%=submit_tag "Click To update User", :class=>"btn"%>
        </td>
      </tr>
  <% end %>

</table>

app/views/managingusers/update_allocated_user_space.html.erb
<div class="alert alert-success">
  <%=flash[:notice]%>
</div>

app/views/resumes/_slider.html.erb
<div class="container">
  <div class="row">

    <div class="span12">
      <div id="myCarousel" class="carousel slide">
        <!-- Carousel slides -->
        <div class="carousel-inner" width="100%" height="100%">
          <div class="active item">
            <%= image_tag 'c.jpg', :style => "width: 1500px; height: 450px;"  %>
            <div class="carousel-caption">
              <h4>
                CAPTION</h4>
              <p>
                Sample Caption</p>
            </div>
          </div>
          <div class="item">
            <%= image_tag 'b.jpg', :style => "width: 1500px; height: 450px;"  %>
          </div>
          <div class="item">
            <%= image_tag 'a.jpg', :style => "width: 1500px; height: 450px;"  %>

          </div>
          <div class="item">
            <%= image_tag 'd.jpg', :style => "width: 1500px; height: 450px;"  %>

          </div>
        </div>
        <!-- Carousel navigation -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a> <a class="carousel-control right"
                                                                                       href="#myCarousel" data-slide="next">›</a>
      </div>
    </div>
  </div>

</div>
<br><br><br><br>
<div class="row">
  <div class="span4">
    <h4 class="muted text-center">Meet Our Clients</h4>
    <p>Donec id elit non mi Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.</p>
    <a href="#" class="btn"><i class="icon-user"></i> Our Clients</a>
  </div>
  <div class="span4">
    <h4 class="muted text-center">Know Our Employees</h4>
    <p>Donec id elit non mi Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.</p>
    <a href="#" class="btn btn-success"><i class="icon-star icon-white"></i> Our Employees</a>
  </div>
    <div class="span4">
        <h4 class="muted text-center">Reach Us</h4>
        <div class="row">
            <div class="span4">
            </div>

        <div class="span8">
            <address>
            <strong >Cloud Storage</strong><br>
            Visit Us: <%= link_to 'cloudstorage.pk', root_url %><br>
            54-M,Gulberg-III<br>
            Lahore <abbr title="Phone">P:</abbr>(345) 6565187
            </address>
            <%=link_to 'Contact Us',new_inquiry_path, class: "btn btn-info"%>
        </div>
        </div>
  </div>
</div>
<br>
</div>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<%= link_to "connect to your dorpbox accoutn", resumes_reg_url  %>

<%= link_to "show uploaded files",  resumes_show_path  %>


<% if !flash[:notice].blank? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>

<br />

<%= link_to "Upload File", new_resume_path, class: "btn btn-primary" %>

<br />
<br />

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
    <div class="alert alert-error">
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %><br />
      Enter code here<%#= text_field_tag :code  %> <br />
      <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/resumes/reg.html.erb
<a href="<%=@authorize_url%>" target="_blank">Click here to copy the access code</a>


<div class="well">
  <%= form_tag({:action => :connect}, :method => :post) do %>
      <%=text_field_tag :code %>
      <%=submit_tag :submit%>
  <%end%>

</div>

app/views/resumes/show.html.erb
<table class="table table-bordered table-striped">
  <thead>
  <tr>

    <th>revision</th>
    <th>rev </th>

    <th>thumb_exists</th>
    <th>bytes</th>
    <th>modified</th>
    <th>client_mtime</th>
    <th> path </th>
    <th> is_dir </th>
    <th> icon </th>
    <th> root </th>
    <th> size </th>


  </tr>
  </thead>
  <tbody>


   <%#=@root_metadata.collect{|k, v| k << v}  %>

  <% @root_metadata.each_pair do |k,v| %>
      <%  if k == "contents" %>
          <% v.each do |k,v| %>
              <tr>
              <%  k.each do |k,v| %>
                      <% if k== "path"  %>
                        <td><a href="<%=v %>"><%=v %></a> </td>
                        <% else%>
                            <td><%=v %></td>
                    <% end %>



              <% end %>
              </tr>
          <%end %>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/resumes/sms.html.erb
<%= link_to 'send request', sms_resumes_path %>